### ISSUE TITLE
What is the serial output of the serv cores?

### ISSUE THREAD

**Issue by imuguruza** [olofk/corescore#2]
Hi!

I am trying to port the Alhambra board. I am already synthesizing and loading the design.
I would like to know which is the output of the serial port of the design, to see if it is working OK and the baud-rate (to launch `corecount.py`)

Thx

**Comment by olofk** [comment]
corecount.py expects a baud rate of 57600, which you normally get with a 16MHz clock. This should of course be possible to change as a parameter, but if you can use a 16MHz clock that would the easiest to begin with

**Comment by olofk** [comment]
And the data format uses msgpack, but most of it will look like regular ascii strings, so you can just use a regular terminal to see if data comes out

**Comment by imuguruza** [comment]
>corecount.py expects a baud rate of 57600, which you normally get with a 16MHz clock. This should of course be possible to change as a parameter, but if you can use a 16MHz clock that would the easiest to begin with

As with `servant`, the hw I am using has a 12MHz oscillator, so I will try again to lower down the baudrate. But I believe that the system clock used is the one generated by the `PLL`, so if I configure properly the instantiation, it should work to the same speed as others.

>And the data format uses msgpack, but most of it will look like regular ascii strings, so you can just use a regular terminal to see if data comes out

Yes, I have seen the characters, but they look like rubbish, that's why I wanted to know if there is any specific string I should search for

**Comment by imuguruza** [comment]
Ok, now I see that the `upduino2` uses the `pll` to divide the `hfosc` clock and generate 16MHz. That was confusing me

**Comment by imuguruza** [comment]
I have udpated my design to use `pll` to create a 16MHz clock. So now I am able to see the cores output using 57600 baudrate:

```bash
�Core000 says hello
                                                       �Core001 says hello
                                                                         �Core002 says hello
                  �Core003 says hello
                                     �Core004 says hello
                                                        �Core005 says hello
```
Now if I execute `corecount.py`, I receive the next error:
```
Traceback (most recent call last):
  File "sw/corecount.py", line 50, in <module>
    curses.wrapper(main)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "sw/corecount.py", line 39, in main
    u = umsgpack.unpack(ser, unicode_errors="True")
  File "/home/inigo/.local/lib/python3.6/site-packages/msgpack/__init__.py", line 46, in unpack
    return unpackb(data, **kwargs)
  File "msgpack/_unpacker.pyx", line 206, in msgpack._cmsgpack.unpackb
ValueError: Unpack failed: incomplete input
```
Which could be due to the end of the each core string, a "0xB4" character is send:

```
43 6F 72 65 30 30 38 20 - 73 61 79 73 20 68 65 6C    Core008   says hel
6C 6F 0A 00 B4 43 6F 72 - 65 30 30 39 20 73 61 79    lo...Cor  e009 say
```

This table shows the hexadecimal values received by the serial, and the corresponding ASCII characters.

Have you seen this behavior before @olofk ?
Thanks for your support :)

**Comment by olofk** [comment]
I think that sometimes you can hit a bad point in the stream, but in my experience it should just be to restart corecount when that happens and it usually works the second time. It's all just a quick and dirty hack :) 

Or is this an issue that comes up all the time? In that case it might need more investigation

**Comment by imuguruza** [comment]
Yes, I am not able to run properly `corecount.py`, it always return that error. I have check the serial port, and at the end of each core print, it always add that 0xB4. I believe that, as it is not an ASCII character, it throws an exception in `unpcack` call

**Comment by olofk** [comment]
It's correct that 0xb4 isn't an ascii character, but if you look at the [msgpack spec](https://github.com/msgpack/msgpack/blob/master/spec.md#str-format-family), it means it's a string with 20 characters (0xb4 = 10110100 = 101 10100 = fixstr 20)

I think the problem is something else but I have no idea what. Could you try to change the unpack line to `u = umsgpack.unpack(ser, allow_invalid_utf8=True)` and see if that makes any different. I'm digging deep inside of umsgpack now to look for clues

**Comment by olofk** [comment]
Would also be good to know what version of umsgpack you're using so I can try the same version. The code I'm looking at can't even throw the error from that's in your Traceback

**Comment by olofk** [comment]
My main theory now is that we're using different implementations of msgpack. I'm using the one that is called `u-msgpack-python` by pip. But your traceback seems to match another implementation.

**Comment by imuguruza** [comment]
You were right! I didn't realize that I was using another python library...
I have uninstalled some python msg packages and installed `u-msgpack-python`. Now it works:

![Screenshot from 2020-05-13 08-30-22](https://user-images.githubusercontent.com/7628788/81779140-62476a80-94f4-11ea-8197-0f9a7ed497cb.png)

I have been able to fit 12 cores in the iCE40hx4k

**Comment by olofk** [comment]
Great! A bit scary that another python package also can be loaded with `import umsgpack`. Not sure how to detect this properly. Best would of course be a software that work with both packages. Oh well.

Btw, it's actually 13 cores, since the core that is used to print to the UART isn't counted here :)

**Comment by imuguruza** [comment]
Here you have the iCE40hx4k resource utilization, taken from `next.log`

```Info: Device utilisation:
Info: 	         ICESTORM_LC:  5969/ 7680    77%
Info: 	        ICESTORM_RAM:    15/   32    46%
Info: 	               SB_IO:     3/  256     1%
Info: 	               SB_GB:     6/    8    75%
Info: 	        ICESTORM_PLL:     1/    2    50%
Info: 	         SB_WARMBOOT:     0/    1     0%
```

I will open a PR in short :-)

**Comment by imuguruza** [comment]
Closing the issue!
